[versions]
kotlin = "2.2.10"
ktor = "3.2.3"
jib = "3.4.5"
slf4j = "2.0.17"
logback = "1.5.18"
logstashLogbackEncoder = "8.1"
opentelemetry = "1.56.0"
opentelemetry-google-cloud = "0.36.0"

[libraries]
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = {module = "ch.qos.logback:logback-classic", version.ref = "logback"}
logback-logstash-encoder = {module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashLogbackEncoder"}
opentelemetry-bom = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "opentelemetry" }
opentelemetry-google-cloud = { module = "com.google.cloud.opentelemetry:exporter-metrics", version.ref = "opentelemetry-google-cloud" }

[plugins]
kotlin-jvm           = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jib                  = { id = "com.google.cloud.tools.jib", version.ref = "jib" }